apiVersion: v1
kind: Service
metadata:
  name: image-classifier-service
spec:
  selector:
    app: image-classifier
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8501
  type: {{ .Values.service.type }}
